import { defineType } from "sanity";
import { field, image } from "./shared";
export const labelKeys = [
  "occasionGuests",
  "foodMenu",
  "drinksWine",
  "welcomeCocktail",
  "wineSelection",
  "menusCompleted",
  "chooseMenu",
  "menuSelected",
  "priceDetails",
  "baseExperience",
  "additionalGuests",
  "menuSupplements",
  "drinkSupplements",
  "extras",
  "addGuest",
  "removeGuest",
  "noExtras",
  "cocktails",
  "cocktailHint",
  "completeHint",
  "capacityPending",
  "vegan",
  "vegetarian",
  "proposalSectionTitle",
  "proposalSectionDescription",
  "dinnerSectionTitle",
  "dinnerSectionDescription",
  "currencySymbol",
  "estimatedTotalLabel",
  "availabilityButtonLabel",
  "includedLabel",
  "startingAtLabel",
  "selectStyleLabel",
  "addonsLabel",
  "contactUsLabel",
  "emptyProposals",
  "emptyDinners",
  "fullName",
  "email",
  "phone",
  "hotel",
  "desiredDate",
  "notes",
  "send",
  "success",
  "error",
  "guests",
  "guest",
  "occasion",
  "customOccasion",
  "starter",
  "main",
  "dessert",
  "beverages",
  "duration",
  "minutes",
  "quantity",
  "quotePending",
  "select",
  "menu",
  "previous",
  "next",
  "photo",
  "privacy",
  "terms",
];
export default defineType({
  name: "experienceCatalogSettings",
  type: "document",
  title: "Catalog Settings",
  fields: labelKeys.map((k) => field(k, "localizedString")),
});
export const catalogHome = defineType({
  name: "catalogHome",
  type: "document",
  title: "Home",
  fields: [
    image("heroImage"),
    ...[
      "eyebrow",
      "headline",
      "subheadline",
      "primaryCTA",
      "secondaryCTA",
      "contactHeading",
    ].map((k) => field(k, "localizedString")),
    field("seo", "experienceSeo"),
  ],
});
export const catalogContact = defineType({
  name: "catalogContact",
  type: "document",
  title: "Contact",
  fields: [
    ...["heading", "description", "businessInformation"].map((k) =>
      field(k, "localizedText"),
    ),
    field("telephone"),
    field("email"),
    field("whatsapp"),
    field("seo", "experienceSeo"),
  ],
});
