import { homeCopy } from "@/lib/experience/homeCopy";
import { introductionLabels } from "@/lib/experience/introduction";
import { dinnerPolicyLabels } from "@/lib/experience/dinnerPolicy";
import { defineType, defineField } from "sanity";
import { field, image } from "./shared";
export const labelKeys = [
  "navHome",
  "navProposals",
  "navDinners",
  "navHow",
  "navFaq",
  "planProposal",
  "planCelebration",
  "fragranceSensitivity",
  "occasionGuests",
  "foodMenu",
  "drinksWine",
  "welcomeCocktail",
  "wineSelection",
  "menusCompleted",
  "chooseMenu",
  "menuSelected",
  "priceDetails",
  "baseExperience",
  "additionalGuests",
  "menuSupplements",
  "drinkSupplements",
  "extras",
  "addGuest",
  "removeGuest",
  "noExtras",
  "cocktails",
  "cocktailHint",
  "completeHint",
  "capacityPending",
  "vegan",
  "vegetarian",
  "proposalSectionTitle",
  "proposalSectionDescription",
  "dinnerSectionTitle",
  "dinnerSectionDescription",
  "currencySymbol",
  "estimatedTotalLabel",
  "availabilityButtonLabel",
  "includedLabel",
  "startingAtLabel",
  "selectStyleLabel",
  "addonsLabel",
  "contactUsLabel",
  "emptyProposals",
  "emptyDinners",
  "fullName",
  "email",
  "phone",
  "hotel",
  "desiredDate",
  "notes",
  "send",
  "success",
  "error",
  "guests",
  "guest",
  "occasion",
  "customOccasion",
  "starter",
  "main",
  "dessert",
  "beverages",
  "duration",
  "minutes",
  "quantity",
  "quotePending",
  "select",
  "menu",
  "previous",
  "next",
  "photo",
  "selectPackage",
  "selectedPackage",
  "blog",
  "faq",
  "previewOnly",
  "privacy",
  "terms",
];
export default defineType({
  name: "experienceCatalogSettings",
  type: "document",
  title: "Catalog Settings",
  initialValue: {
    dinnerDepositAmount: 200,
    ...Object.fromEntries(
      Object.entries(dinnerPolicyLabels).map(([key, [en, es]]) => [
        key,
        { en, es },
      ]),
    ),
  },
  fields: [
    defineField({
      name: "dinnerDepositAmount",
      title: "Dinner deposit (USD)",
      type: "number",
      initialValue: 200,
      validation: (rule) => rule.positive().precision(2),
      description:
        "Requested manually only after availability is confirmed. Use {deposit} in the policy messages.",
    }),
    ...Object.keys(dinnerPolicyLabels).map((k) => field(k, "localizedText")),
    ...labelKeys.map((k) => field(k, "localizedString")),
    ...Object.keys(introductionLabels).map((k) => field(k, "localizedText")),
  ],
});
export const catalogHome = defineType({
  name: "catalogHome",
  type: "document",
  title: "Home",
  initialValue: {
    copy: Object.fromEntries(
      Object.entries(homeCopy).map(([key, [en, es]]) => [key, { en, es }]),
    ),
  },
  fields: [
    image("heroImage"),
    image("proposalHeroImage"),
    image("dinnerHeroImage"),
    image("proposalSelectorImage"),
    image("dinnerSelectorImage"),
    defineField({
      name: "copy",
      title: "Home page text (EN / ES)",
      type: "object",
      fields: Object.keys(homeCopy).map((k) => field(k, "localizedText")),
    }),
    defineField({
      name: "featuredProposals",
      type: "array",
      title: "Featured proposals (up to three, ordered)",
      of: [
        {
          type: "reference",
          to: [{ type: "proposalExperience" }],
        },
      ],
      validation: (r) => r.max(3).unique(),
    }),
    ...["journeyImages", "editorialImages", "moments"].map((name) =>
      defineField({
        name,
        type: "array",
        of: [image("photo")],
        validation: (r) => r.max(name === "journeyImages" ? 5 : 8),
      }),
    ),
    ...[
      "eyebrow",
      "headline",
      "subheadline",
      "primaryCTA",
      "secondaryCTA",
      "contactHeading",
    ].map((k) => field(k, "localizedString")),
    field("seo", "experienceSeo"),
  ],
});
export const catalogContact = defineType({
  name: "catalogContact",
  type: "document",
  title: "Contact",
  fields: [
    ...["heading", "description", "businessInformation"].map((k) =>
      field(k, "localizedText"),
    ),
    field("telephone"),
    field("email"),
    field("whatsapp"),
    field("seo", "experienceSeo"),
  ],
});
