// Approved menu supplied by the owner. Used only to populate the existing Sanity schemas.
const l = (en: string, es: string) => ({ en, es });
const dishes = [
  [
    "starter",
    "mediterranean-salad",
    "Mediterranean Salad",
    "Ensalada mediterránea",
    "Sun-dried tomatoes, peppers, cucumber, olives, basil leaves, and cherry confit vinaigrette.",
    "Tomates secos, pimientos, pepino, aceitunas, hojas de albahaca y vinagreta de cerezas confitadas.",
    "vegan",
  ],
  [
    "starter",
    "caesar-salad",
    "Traditional Caesar Salad",
    "Ensalada César tradicional",
    "Parmesan shavings and grissini.",
    "Lascas de parmesano y grissini.",
    "regular",
  ],
  [
    "starter",
    "beef-carpaccio",
    "Beef Carpaccio",
    "Carpaccio de res",
    "Served with vinaigrette, Parmesan cheese slices, and fresh arugula.",
    "Con vinagreta, láminas de parmesano y rúcula fresca.",
    "regular",
  ],
  [
    "starter",
    "smoked-salmon-salad",
    "Smoked Salmon Salad",
    "Ensalada de salmón ahumado",
    "Served with caramelized pineapple cubes.",
    "Con cubos de piña caramelizada.",
    "regular",
  ],
  [
    "starter",
    "goat-cheese-salad",
    "Goat Cheese Salad",
    "Ensalada de queso de cabra",
    "Caramelized walnuts, grapes, and mustard vinaigrette.",
    "Nueces caramelizadas, uvas y vinagreta de mostaza.",
    "vegetarian",
  ],
  [
    "starter",
    "melon-salad",
    "Melon Salad",
    "Ensalada de melón",
    "Crispy ham and balsamic dressing.",
    "Jamón crujiente y aderezo balsámico.",
    "regular",
  ],
  [
    "starter",
    "caprese",
    "Traditional Caprese",
    "Caprese tradicional",
    "",
    "",
    "vegetarian",
  ],
  [
    "starter",
    "fish-tartare",
    "Salmon or Tuna Tartare",
    "Tartar de salmón o atún",
    "Served with citrus dressing.",
    "Con aderezo cítrico.",
    "regular",
  ],
  [
    "starter",
    "fake-caprese",
    "Fake Caprese",
    "Falsa caprese",
    "Tofu, tomato, and pesto.",
    "Tofu, tomate y pesto.",
    "vegan",
  ],
  [
    "main",
    "chicken-involtini",
    "Chicken Involtini",
    "Involtini de pollo",
    "Stuffed with spinach, served over truffled potatoes and sautéed mushrooms with meat jus.",
    "Relleno de espinacas, sobre patatas trufadas y champiñones salteados con jugo de carne.",
    "regular",
  ],
  [
    "main",
    "salmon-puff-pastry",
    "Salmon on Puff Pastry",
    "Salmón sobre hojaldre",
    "Creamy spinach, curry rice, and cava sauce.",
    "Espinacas cremosas, arroz al curry y salsa de cava.",
    "regular",
  ],
  [
    "main",
    "fish-fillet",
    "Fish Fillet Loin",
    "Lomo de pescado",
    "Carrot purée and roasted vegetables.",
    "Puré de zanahoria y vegetales asados.",
    "regular",
  ],
  [
    "main",
    "grilled-tuna",
    "Grilled Tuna Medallion",
    "Medallón de atún a la parrilla",
    "Served with coconut shrimp rice.",
    "Con arroz de coco y camarones.",
    "regular",
  ],
  [
    "main",
    "pork-tenderloin",
    "Pork Tenderloin Medallion",
    "Medallón de solomillo de cerdo",
    "Wrapped in bacon with truffled potato purée and caramelized onion.",
    "Envuelto en tocino, con puré de patatas trufadas y cebolla caramelizada.",
    "regular",
  ],
  [
    "main",
    "beef-fillet",
    "Grilled Beef Fillet",
    "Filete de res a la parrilla",
    "Served with potato mille-feuille and mushrooms.",
    "Con milhojas de patata y champiñones.",
    "regular",
  ],
  [
    "main",
    "mushroom-rice",
    "Creamy Mushroom Rice",
    "Arroz cremoso de champiñones",
    "Served with light white asparagus cream and almonds.",
    "Con crema ligera de espárragos blancos y almendras.",
    "vegan",
  ],
  [
    "main",
    "roasted-eggplant",
    "Roasted Eggplant",
    "Berenjena asada",
    "Stuffed with spiced lentils and aromatic herbs.",
    "Rellena de lentejas especiadas y hierbas aromáticas.",
    "vegan",
  ],
  [
    "dessert",
    "cheesecake",
    "New York Cheesecake",
    "Cheesecake estilo Nueva York",
    "Served with passion fruit sauce.",
    "Con salsa de maracuyá.",
    "regular",
  ],
  ["dessert", "tiramisu", "Tiramisu", "Tiramisú", "", "", "regular"],
  [
    "dessert",
    "brownie",
    "Chocolate Brownie",
    "Brownie de chocolate",
    "Served with ice cream.",
    "Con helado.",
    "regular",
  ],
  [
    "dessert",
    "panna-cotta",
    "Almond Milk Panna Cotta",
    "Panna cotta de leche de almendras",
    "Served with red fruits.",
    "Con frutos rojos.",
    "vegan",
  ],
  [
    "dessert",
    "carrot-cake",
    "Raw Carrot Cake",
    "Pastel crudivegano de zanahoria",
    "Served with cream glaze.",
    "Con glaseado de crema.",
    "vegan",
  ],
  [
    "dessert",
    "pineapple",
    "Caramelized Pineapple",
    "Piña caramelizada",
    "Prepared with rum and coconut.",
    "Preparada con ron y coco.",
    "vegan",
  ],
];
export const approvedMenu = dishes.map(
  (
    [courseType, key, en, es, descriptionEn, descriptionEs, dietaryType],
    displayOrder,
  ) => ({
    _id: "dinner-menu-" + key,
    _type: "menuItem",
    name: l(en, es),
    description: l(descriptionEn, descriptionEs),
    courseType,
    dietaryType,
    included: true,
    supplementPrice: 0,
    active: true,
    displayOrder,
  }),
);
const drinks = [
  [
    "mojito",
    "Mojito",
    "Mojito",
    "White rum, lime, mint, sugar, and soda water.",
    "Ron blanco, lima, menta, azúcar y soda.",
  ],
  [
    "caipirinha",
    "Caipirinha",
    "Caipiriña",
    "Cachaça, fresh lime, and sugar.",
    "Cachaça, lima fresca y azúcar.",
  ],
  [
    "cuba-libre",
    "Cuba Libre",
    "Cuba libre",
    "Rum, Coca-Cola, and fresh lime.",
    "Ron, Coca-Cola y lima fresca.",
  ],
  [
    "pina-colada",
    "Piña Colada",
    "Piña colada",
    "Rum, coconut cream, and pineapple juice.",
    "Ron, crema de coco y jugo de piña.",
  ],
  [
    "margarita",
    "Margarita",
    "Margarita",
    "Tequila, orange liqueur, and fresh lime juice.",
    "Tequila, licor de naranja y jugo de lima fresco.",
  ],
  [
    "daiquiri",
    "Daiquiri",
    "Daiquirí",
    "White rum, fresh lime juice, and sugar.",
    "Ron blanco, jugo de lima fresco y azúcar.",
  ],
  [
    "tequila-sunrise",
    "Tequila Sunrise",
    "Tequila Sunrise",
    "Tequila, orange juice, and grenadine.",
    "Tequila, jugo de naranja y granadina.",
  ],
  [
    "rum-punch",
    "Rum Punch",
    "Ponche de ron",
    "Rum with tropical fruit juices.",
    "Ron con jugos de frutas tropicales.",
  ],
  [
    "gin-tonic",
    "Gin & Tonic",
    "Gin tonic",
    "Gin, tonic water, and fresh citrus.",
    "Ginebra, agua tónica y cítricos frescos.",
  ],
  [
    "vodka-lemon",
    "Vodka Lemon",
    "Vodka limón",
    "Vodka, lemon-lime soda, and fresh lime.",
    "Vodka, refresco de lima-limón y lima fresca.",
  ],
  ["red-wine", "Red Wine", "Vino tinto", "", ""],
  ["white-wine", "White Wine", "Vino blanco", "", ""],
  ["sparkling-wine", "Sparkling Wine", "Vino espumante", "", ""],
];
export const approvedBeverages = drinks.map(
  ([key, en, es, descriptionEn, descriptionEs], displayOrder) => ({
    _id: "dinner-beverage-" + key,
    _type: "beverageOption",
    name: l(en, es),
    description: l(descriptionEn, descriptionEs),
    type:
      displayOrder < 10
        ? "welcomeDrink"
        : key === "sparkling-wine"
          ? "sparkling"
          : "wine",
    included: true,
    supplementPrice: 0,
    active: true,
    displayOrder,
  }),
);
export const approvedAddons = [
  ["photographer", "Professional Photographer", "Fotógrafo profesional", 299],
  ["videographer", "Professional Videographer", "Videógrafo profesional", 449],
].map(([key, en, es, price], displayOrder) => ({
  _id: "dinner-addon-" + key,
  _type: "experienceAddon",
  name: l(String(en), String(es)),
  pricingType: "fixed",
  price,
  applicableTo: ["romanticDinner"],
  active: true,
  displayOrder,
}));
export const approvedDinnerPrices = {
  basePrice: 849,
  currency: "USD",
  includedGuests: 2,
  minimumGuests: 2,
  additionalGuestPrice: 100,
  includedDurationMinutes: 120,
};
