import type { DefaultText, Locale, Home } from "./types";
export const homeCopy: Record<string, DefaultText> = {
  eyebrow: {
    en: "PRIVATE PROPOSAL EXPERIENCES IN PUNTA CANA",
    es: "PROPUESTAS DE MATRIMONIO PRIVADAS EN PUNTA CANA",
    fr: "DEMANDES EN MARIAGE PRIVÉES À PUNTA CANA",
    pt: "PEDIDOS DE CASAMENTO PRIVATIVOS EM PUNTA CANA",
  },
  headline: {
    en: "Your Perfect Yes, Beautifully Planned.",
    es: "Tu sí perfecto, planeado con cada detalle.",
    fr: "Votre « oui » parfait, magnifiquement orchestré.",
    pt: "O seu sim perfeito, lindamente planejado.",
  },
  introduction: {
    en: "We design and coordinate private marriage proposals in Punta Cana, combining breathtaking beachfront settings, thoughtful decoration, professional photography and seamless transportation. You arrive, live the moment and let us take care of everything else.",
    es: "Diseñamos y coordinamos propuestas de matrimonio privadas en Punta Cana: escenarios frente al mar, decoración cuidada, fotografía profesional y transporte privado. Tú llegas y vives el momento; nosotros nos encargamos de los detalles.",
    fr: "Nous concevons et coordonnons des demandes en mariage privées à Punta Cana, en réunissant des cadres époustouflants en bord de mer, une décoration soignée, une photographie professionnelle et un transport sans le moindre souci. Vous arrivez, vous vivez l’instant, et nous nous occupons de tout le reste.",
    pt: "Criamos e coordenamos pedidos de casamento privativos em Punta Cana, reunindo cenários deslumbrantes à beira-mar, decoração cuidadosa, fotografia profissional e transporte sem preocupações. Você chega, vive o momento e deixa todo o resto com a gente.",
  },
  exploreProposals: {
    en: "Explore proposal packages",
    es: "Explora los paquetes de propuestas",
    fr: "Découvrir les forfaits demande en mariage",
    pt: "Conheça os pacotes de pedido de casamento",
  },
  exploreDinners: {
    en: "Discover private dinners",
    es: "Descubre las cenas privadas",
    fr: "Découvrir les dîners privés",
    pt: "Descubra os jantares privativos",
  },
  deposit: {
    en: "After availability is confirmed, reserve with {deposit}. Pay the remaining balance on the day of your experience.",
    es: "Después de confirmar disponibilidad, reserva con {deposit}. Paga el balance restante el día de la experiencia.",
    fr: "Une fois la disponibilité confirmée, réservez avec {deposit}. Le solde est à régler le jour de votre expérience.",
    pt: "Depois que a disponibilidade for confirmada, reserve com {deposit}. Pague o saldo restante no dia da sua experiência.",
  },
  planning: {
    en: "What Are You Planning?",
    es: "¿Qué te gustaría celebrar?",
    fr: "Que souhaitez-vous organiser ?",
    pt: "O que você está planejando?",
  },
  proposalChoice: {
    en: "A Marriage Proposal",
    es: "Una propuesta de matrimonio",
    fr: "Une demande en mariage",
    pt: "Um pedido de casamento",
  },
  proposalDescription: {
    en: "Private beachfront settings, thoughtful decoration, professional photography and complete coordination for your once-in-a-lifetime question.",
    es: "Montajes privados frente al mar, decoración cuidada, fotografía profesional y coordinación para esa pregunta única en la vida.",
    fr: "Des cadres privés en bord de mer, une décoration soignée, une photographie professionnelle et une coordination complète pour la question d’une vie.",
    pt: "Cenários privativos à beira-mar, decoração cuidadosa, fotografia profissional e coordenação completa para a pergunta mais importante da sua vida.",
  },
  dinnerChoice: {
    en: "A Private Dinner or Celebration",
    es: "Una cena privada o celebración",
    fr: "Un dîner privé ou une célébration",
    pt: "Um jantar privativo ou uma celebração",
  },
  dinnerDescription: {
    en: "A gourmet three-course dinner directly in front of the sea, with a dedicated waiter, private transportation and a setting reserved exclusively for your party.",
    es: "Una cena gourmet de tres tiempos frente al mar, con camarero dedicado, transporte privado y un espacio exclusivo para tu pareja o grupo.",
    fr: "Un dîner gastronomique en trois plats face à la mer, avec un serveur dédié, un transport privé et un cadre réservé exclusivement à vous et vos invités.",
    pt: "Um jantar gourmet de três tempos de frente para o mar, com garçom exclusivo, transporte privativo e um espaço reservado só para o seu grupo.",
  },
  trustPrivate: {
    en: "Private beachfront experiences",
    es: "Experiencias privadas frente al mar",
    fr: "Expériences privées en bord de mer",
    pt: "Experiências privativas à beira-mar",
  },
  trustLocal: {
    en: "Local Punta Cana coordination",
    es: "Coordinación local en Punta Cana",
    fr: "Coordination locale à Punta Cana",
    pt: "Coordenação local em Punta Cana",
  },
  trustTransport: {
    en: "Private round-trip transportation",
    es: "Transporte privado de ida y vuelta",
    fr: "Transport privé aller-retour",
    pt: "Transporte privativo de ida e volta",
  },
  trustService: {
    en: "Dedicated service",
    es: "Servicio dedicado",
    fr: "Service dédié",
    pt: "Atendimento exclusivo",
  },
  trustPhoto: {
    en: "Professional photography · 35–40 edited photographs",
    es: "Fotografía profesional · 35–40 fotografías editadas",
    fr: "Photographie professionnelle · 35–40 photos retouchées",
    pt: "Fotografia profissional · 35–40 fotos editadas",
  },
  trustDelivery: {
    en: "Photos within 48 hours · video within 10 days",
    es: "Fotos en 48 horas · video en 10 días",
    fr: "Photos sous 48 heures · vidéo sous 10 jours",
    pt: "Fotos em até 48 horas · vídeo em até 10 dias",
  },
  mediaNote: {
    en: "Photography and video delivery apply when those services are included or added to your experience.",
    es: "La entrega de fotografías y video aplica cuando estos servicios están incluidos o se añaden a tu experiencia.",
    fr: "Les délais de livraison des photos et de la vidéo s’appliquent lorsque ces services sont inclus ou ajoutés à votre expérience.",
    pt: "A entrega de fotos e vídeo se aplica quando esses serviços estão incluídos ou são adicionados à sua experiência.",
  },
  journeyTitle: {
    en: "Your Experience Begins Before You Reach the Beach",
    es: "Tu experiencia comienza antes de llegar a la playa",
    fr: "Votre expérience commence avant même d’arriver sur la plage",
    pt: "Sua experiência começa antes de você chegar à praia",
  },
  journeyIntro: {
    en: "From your accommodation to your safe return, every detail is coordinated personally. Dinners take place in Cabeza de Toro, Punta Cana. Your proposal location is confirmed according to the chosen package.",
    es: "Desde tu alojamiento hasta el regreso seguro, coordinamos personalmente cada detalle. Las cenas se realizan en Cabeza de Toro, Punta Cana. La ubicación de tu propuesta se confirma según el paquete elegido.",
    fr: "De votre hébergement jusqu’à votre retour en toute sécurité, chaque détail est coordonné personnellement. Les dîners ont lieu à Cabeza de Toro, Punta Cana. Le lieu de votre demande en mariage est confirmé selon le forfait choisi.",
    pt: "Da sua hospedagem até o seu retorno em segurança, cada detalhe é coordenado pessoalmente. Os jantares acontecem em Cabeza de Toro, Punta Cana. O local do seu pedido é confirmado de acordo com o pacote escolhido.",
  },
  journeyOne: {
    en: "Meet Your Driver",
    es: "Conoce a tu chofer",
    fr: "Faites connaissance avec votre chauffeur",
    pt: "Conheça seu motorista",
  },
  journeyOneText: {
    en: "Before your experience, you will receive your driver’s name, photograph, vehicle details and exact pickup information privately, so you know exactly who will be waiting for you. Your driver is professionally dressed, identified and familiar with your itinerary.",
    es: "Antes de la experiencia recibirás en privado el nombre y fotografía de tu chofer, los datos del vehículo, la hora de recogida y el punto de encuentro. Un chofer profesional, bien vestido e identificado conocerá tu itinerario.",
    fr: "Avant votre expérience, vous recevrez en privé le nom et la photo de votre chauffeur, les informations sur le véhicule et les détails précis de la prise en charge, pour savoir exactement qui vous attendra. Votre chauffeur est vêtu de manière professionnelle, identifié et connaît votre itinéraire.",
    pt: "Antes da sua experiência, você receberá em particular o nome e a foto do seu motorista, os dados do veículo e as informações exatas de embarque, para saber exatamente quem estará esperando por você. Seu motorista estará bem-vestido, identificado e familiarizado com o seu itinerário.",
  },
  journeyTwo: {
    en: "Comfortable Private Transportation",
    es: "Transporte privado y cómodo",
    fr: "Un transport privé et confortable",
    pt: "Transporte privativo e confortável",
  },
  journeyTwoText: {
    en: "Step into a clean, comfortable and pleasantly scented vehicle prepared with snacks and beverages for your journey. Let us know about fragrance sensitivities in your request.",
    es: "Te espera un vehículo limpio, cómodo y cuidadosamente aromatizado, con snacks y bebidas para el traslado. Indica cualquier sensibilidad a fragancias en tu solicitud.",
    fr: "Installez-vous dans un véhicule propre, confortable et délicatement parfumé, avec des en-cas et des boissons pour le trajet. Signalez-nous toute sensibilité aux parfums dans votre demande.",
    pt: "Embarque em um veículo limpo, confortável e agradavelmente perfumado, preparado com petiscos e bebidas para o trajeto. Informe qualquer sensibilidade a fragrâncias na sua solicitação.",
  },
  journeyThree: {
    en: "Arrive at the Beach",
    es: "Llega a la playa",
    fr: "Arrivée sur la plage",
    pt: "Chegue à praia",
  },
  journeyThreeText: {
    en: "Your setting is prepared before you arrive. For dinners, your private table awaits by the sea in Cabeza de Toro. Proposal settings depend on your selected package.",
    es: "Tu montaje estará preparado antes de llegar. Para las cenas, tu mesa privada te espera frente al mar en Cabeza de Toro. El escenario de una propuesta depende del paquete seleccionado.",
    fr: "Votre décor est prêt avant votre arrivée. Pour les dîners, votre table privée vous attend face à la mer à Cabeza de Toro. Le cadre des demandes en mariage dépend du forfait choisi.",
    pt: "Sua ambientação estará pronta antes da sua chegada. Nos jantares, sua mesa privativa espera por você à beira-mar em Cabeza de Toro. O cenário do pedido depende do pacote selecionado.",
  },
  journeyFour: {
    en: "Enjoy Your Private Experience",
    es: "Disfruta tu experiencia privada",
    fr: "Profitez de votre expérience privée",
    pt: "Aproveite sua experiência privativa",
  },
  journeyFourText: {
    en: "Live the moment while our team coordinates your setting and dedicated service. Personalize the celebration with photography, video or live music when available.",
    es: "Vive el momento mientras nuestro equipo coordina el montaje y la atención dedicada. Personaliza la celebración con fotografía, video o música en vivo según disponibilidad.",
    fr: "Vivez l’instant pendant que notre équipe coordonne votre décor et un service dédié. Personnalisez la célébration avec de la photographie, de la vidéo ou de la musique live, selon disponibilité.",
    pt: "Viva o momento enquanto nossa equipe coordena a ambientação e o atendimento exclusivo. Personalize a celebração com fotografia, vídeo ou música ao vivo, conforme a disponibilidade.",
  },
  journeyFive: {
    en: "Return Safely",
    es: "Regresa con tranquilidad",
    fr: "Un retour en toute sérénité",
    pt: "Volte com tranquilidade",
  },
  journeyFiveText: {
    en: "Your professional driver takes you safely back to your hotel, villa or accommodation after the experience.",
    es: "Al terminar la experiencia, tu chofer profesional te lleva de regreso a tu hotel, villa o alojamiento.",
    fr: "Après l’expérience, votre chauffeur professionnel vous raccompagne en toute sécurité à votre hôtel, villa ou hébergement.",
    pt: "Depois da experiência, seu motorista profissional leva você em segurança de volta ao seu hotel, villa ou hospedagem.",
  },
  transformation: {
    en: "From an Empty Beach to Your Perfect Moment",
    es: "De la playa a tu momento perfecto",
    fr: "D’une plage déserte à votre moment parfait",
    pt: "De uma praia vazia ao seu momento perfeito",
  },
  transformationText: {
    en: "Every detail is prepared before you arrive, from the first flower and candle to the final position of your private setting.",
    es: "Preparamos cada detalle antes de tu llegada, desde la primera flor y vela hasta la posición final de tu montaje privado.",
    fr: "Chaque détail est préparé avant votre arrivée, de la première fleur et de la première bougie jusqu’à la mise en place finale de votre cadre privé.",
    pt: "Cada detalhe é preparado antes da sua chegada, da primeira flor e vela até a posição final da sua ambientação privativa.",
  },
  editorialNote: {
    en: "An editorial collection of our settings and details.",
    es: "Una selección editorial de nuestros montajes y detalles.",
    fr: "Une sélection éditoriale de nos décors et de nos détails.",
    pt: "Uma seleção editorial das nossas ambientações e detalhes.",
  },
  featured: {
    en: "Find the Proposal That Feels Like You",
    es: "Encuentra la propuesta que habla de ustedes",
    fr: "Trouvez la demande en mariage qui vous ressemble",
    pt: "Encontre o pedido com a cara de vocês",
  },
  customize: {
    en: "Customize this proposal",
    es: "Personaliza esta propuesta",
    fr: "Personnaliser cette demande",
    pt: "Personalize este pedido",
  },
  allProposals: {
    en: "View all proposal packages",
    es: "Ver todos los paquetes de propuestas",
    fr: "Voir tous les forfaits demande en mariage",
    pt: "Ver todos os pacotes de pedido de casamento",
  },
  dinnerTitle: {
    en: "More Than Dinner. A Private Experience by the Sea.",
    es: "Más que una cena. Una experiencia privada frente al mar.",
    fr: "Bien plus qu’un dîner. Une expérience privée face à la mer.",
    pt: "Mais do que um jantar. Uma experiência privativa à beira-mar.",
  },
  dinnerText: {
    en: "This is not a reserved table inside a crowded restaurant. We create a beautifully styled private table directly on the beach in Cabeza de Toro, exclusively for you and your guests. A dedicated waiter serves your gourmet three-course dinner while our private driver handles your pickup and safe return to your accommodation.",
    es: "No es una mesa reservada dentro de un restaurante concurrido. Creamos una mesa privada y cuidadosamente decorada en la playa de Cabeza de Toro, exclusivamente para ti y tus invitados. Un camarero dedicado sirve tu cena gourmet de tres tiempos mientras nuestro chofer se encarga de la recogida y el regreso seguro a tu alojamiento.",
    fr: "Il ne s’agit pas d’une table réservée dans un restaurant bondé. Nous dressons une table privée, magnifiquement décorée, directement sur la plage de Cabeza de Toro, exclusivement pour vous et vos invités. Un serveur dédié vous sert un dîner gastronomique en trois plats, tandis que notre chauffeur privé assure votre prise en charge et votre retour en toute sécurité jusqu’à votre hébergement.",
    pt: "Não é uma mesa reservada dentro de um restaurante lotado. Criamos uma mesa privativa e lindamente decorada diretamente na areia de Cabeza de Toro, exclusivamente para você e seus convidados. Um garçom exclusivo serve seu jantar gourmet de três tempos, enquanto nosso motorista particular cuida do seu embarque e do seu retorno seguro à hospedagem.",
  },
  dinnerCelebrations: {
    en: "The experience begins with two guests and can grow with your celebration. Add friends or family for birthdays, anniversaries, graduations, career milestones or any moment worth celebrating. Group capacity is confirmed by our team.",
    es: "La experiencia comienza con dos invitados y puede crecer con tu celebración. Invita a familiares o amigos para cumpleaños, aniversarios, graduaciones, logros profesionales o cualquier momento especial. Nuestro equipo confirma la capacidad del grupo.",
    fr: "L’expérience commence à deux convives et peut s’agrandir au rythme de votre célébration. Invitez amis ou famille pour un anniversaire, un anniversaire de mariage, une remise de diplôme, une réussite professionnelle ou tout moment qui mérite d’être célébré. La capacité pour les groupes est confirmée par notre équipe.",
    pt: "A experiência começa com dois convidados e pode crescer com a sua celebração. Convide amigos ou familiares para aniversários, bodas, formaturas, conquistas profissionais ou qualquer momento que mereça ser celebrado. A capacidade para grupos é confirmada pela nossa equipe.",
  },
  dinnerPrice: {
    en: "From {basePrice} for {includedGuests} guests · {additionalGuestPrice} per additional guest",
    es: "Desde {basePrice} para {includedGuests} invitados · {additionalGuestPrice} por invitado adicional",
    fr: "À partir de {basePrice} pour {includedGuests} convives · {additionalGuestPrice} par convive supplémentaire",
    pt: "A partir de {basePrice} para {includedGuests} convidados · {additionalGuestPrice} por convidado adicional",
  },
  howTitle: {
    en: "A Beautiful Moment, Thoughtfully Planned",
    es: "Un momento especial, cuidadosamente planeado",
    fr: "Un moment magnifique, pensé avec soin",
    pt: "Um momento especial, planejado com carinho",
  },
  stepOne: {
    en: "Choose Your Experience",
    es: "Elige tu experiencia",
    fr: "Choisissez votre expérience",
    pt: "Escolha sua experiência",
  },
  stepOneText: {
    en: "Select a proposal package or private dinner.",
    es: "Selecciona una propuesta o una cena privada.",
    fr: "Sélectionnez un forfait demande en mariage ou un dîner privé.",
    pt: "Selecione um pacote de pedido de casamento ou um jantar privativo.",
  },
  stepTwo: {
    en: "Personalize the Details",
    es: "Personaliza los detalles",
    fr: "Personnalisez les détails",
    pt: "Personalize os detalhes",
  },
  stepTwoText: {
    en: "Choose the style, occasion, guests, menus and extras.",
    es: "Elige el estilo, la ocasión, los invitados, el menú y los extras.",
    fr: "Choisissez le style, l’occasion, les convives, les menus et les extras.",
    pt: "Escolha o estilo, a ocasião, os convidados, os menus e os extras.",
  },
  stepThree: {
    en: "Request Your Preferred Date",
    es: "Solicita tu fecha preferida",
    fr: "Demandez votre date préférée",
    pt: "Solicite sua data preferida",
  },
  stepThreeText: {
    en: "Send your preferred date for personal confirmation.",
    es: "Envía tu fecha preferida para confirmación personal.",
    fr: "Envoyez votre date préférée pour une confirmation personnalisée.",
    pt: "Envie sua data preferida para confirmação pessoal.",
  },
  stepFour: {
    en: "Reserve with {deposit}",
    es: "Reserva con {deposit}",
    fr: "Réservez avec {deposit}",
    pt: "Reserve com {deposit}",
  },
  stepFourText: {
    en: "Once our team confirms availability, the deposit secures your reservation.",
    es: "Cuando el equipo confirme disponibilidad, el depósito asegura tu reserva.",
    fr: "Dès que notre équipe confirme la disponibilité, l’acompte garantit votre réservation.",
    pt: "Assim que nossa equipe confirmar a disponibilidade, o sinal garante sua reserva.",
  },
  stepFive: {
    en: "Meet Your Driver",
    es: "Conoce a tu chofer",
    fr: "Faites connaissance avec votre chauffeur",
    pt: "Conheça seu motorista",
  },
  stepFiveText: {
    en: "Receive your driver's details privately before pickup.",
    es: "Recibe los datos de tu chofer en privado antes de la recogida.",
    fr: "Recevez en privé les coordonnées de votre chauffeur avant la prise en charge.",
    pt: "Receba em particular os dados do seu motorista antes do embarque.",
  },
  stepSix: {
    en: "Enjoy Your Moment",
    es: "Disfruta tu momento",
    fr: "Profitez de votre moment",
    pt: "Aproveite o seu momento",
  },
  stepSixText: {
    en: "We coordinate the setting, service and transportation.",
    es: "Coordinamos el montaje, la atención y el transporte.",
    fr: "Nous coordonnons le décor, le service et le transport.",
    pt: "Coordenamos a ambientação, o atendimento e o transporte.",
  },
  stepSeven: {
    en: "Return Safely",
    es: "Regresa con tranquilidad",
    fr: "Un retour en toute sérénité",
    pt: "Volte com tranquilidade",
  },
  stepSevenText: {
    en: "Your driver takes you back to your accommodation.",
    es: "Tu chofer te lleva de regreso al alojamiento.",
    fr: "Votre chauffeur vous raccompagne jusqu’à votre hébergement.",
    pt: "Seu motorista leva você de volta à sua hospedagem.",
  },
  stepEight: {
    en: "Receive Your Memories",
    es: "Recibe tus recuerdos",
    fr: "Recevez vos souvenirs",
    pt: "Receba suas lembranças",
  },
  stepEightText: {
    en: "Photos within 48 hours and video within 10 days, when included or added.",
    es: "Fotos en 48 horas y video en 10 días, cuando estén incluidos o contratados.",
    fr: "Photos sous 48 heures et vidéo sous 10 jours, lorsqu’elles sont incluses ou ajoutées.",
    pt: "Fotos em até 48 horas e vídeo em até 10 dias, quando incluídos ou adicionados.",
  },
  realMoments: {
    en: "Real Moments. Lasting Memories.",
    es: "Momentos reales. Recuerdos para siempre.",
    fr: "Des moments vrais. Des souvenirs pour toujours.",
    pt: "Momentos reais. Lembranças para sempre.",
  },
  viewStories: {
    en: "Explore our stories",
    es: "Descubre nuestras historias",
    fr: "Découvrir nos histoires",
    pt: "Conheça nossas histórias",
  },
  galleryOpen: {
    en: "Enlarge photograph",
    es: "Ampliar fotografía",
    fr: "Agrandir la photographie",
    pt: "Ampliar fotografia",
  },
  close: { en: "Close", es: "Cerrar", fr: "Fermer", pt: "Fechar" },
  previous: {
    en: "Previous photograph",
    es: "Fotografía anterior",
    fr: "Photographie précédente",
    pt: "Fotografia anterior",
  },
  next: {
    en: "Next photograph",
    es: "Fotografía siguiente",
    fr: "Photographie suivante",
    pt: "Próxima fotografia",
  },
  startTitle: {
    en: "Let’s Plan Your Perfect Yes",
    es: "Planeemos tu sí perfecto",
    fr: "Préparons votre « oui » parfait",
    pt: "Vamos planejar o seu sim perfeito",
  },
  planningEyebrow: {
    en: "Punta Cana · Private experiences",
    es: "Punta Cana · Experiencias privadas",
    fr: "Punta Cana · Expériences privées",
    pt: "Punta Cana · Experiências privativas",
  },
  trustLabel: {
    en: "Our experience",
    es: "Nuestra experiencia",
    fr: "Notre expérience",
    pt: "Nossa experiência",
  },
  journeyLabel: {
    en: "Your journey",
    es: "Tu recorrido",
    fr: "Votre parcours",
    pt: "Sua jornada",
  },
  howItWorksLink: {
    en: "How it works",
    es: "Cómo funciona",
    fr: "Comment ça marche",
    pt: "Como funciona",
  },
};
export function homeText(
  home: Home | null | undefined,
  locale: Locale,
  key: string,
) {
  // The editor's text (one document per language), then the built-in text
  // in `locale`, then in English.
  return (
    home?.copy?.[key] || homeCopy[key]?.[locale] || homeCopy[key]?.en || ""
  );
}
