import type { DefaultText } from "./types";

export const introductionLabels: Record<string, DefaultText> = {
  proposalIntroTitle: {
    en: "Marriage proposals in Punta Cana",
    es: "Propuestas de matrimonio en Punta Cana",
    fr: "Demandes en mariage à Punta Cana",
    pt: "Pedidos de casamento em Punta Cana",
  },
  proposalIntroDescription: {
    en: "Create a marriage proposal that feels like you. Compare the photographs, included services and starting prices, then personalize your chosen package here on this page.",
    es: "Prepara una propuesta de matrimonio a tu medida. Compara las fotografías, los servicios incluidos y el precio inicial de cada paquete; después personaliza tu elección aquí mismo, sin salir de la página.",
    fr: "Créez une demande en mariage qui vous ressemble. Comparez les photographies, les services inclus et les prix de départ, puis personnalisez le forfait choisi ici même, sur cette page.",
    pt: "Crie um pedido de casamento com a cara de vocês. Compare as fotografias, os serviços incluídos e os preços iniciais e, depois, personalize o pacote escolhido aqui mesmo, nesta página.",
  },
  proposalIntroStep1Title: {
    en: "Choose your package and style",
    es: "Elige tu paquete y estilo",
    fr: "Choisissez votre forfait et votre style",
    pt: "Escolha seu pacote e estilo",
  },
  proposalIntroStep1: {
    en: "Browse the cards and select an available style from its dropdown. The photographs and price update to match your choice. Click the card or Select package to continue configuring it.",
    es: "Explora los cards y elige uno de sus estilos disponibles en el selector. Las fotografías y el precio se actualizan según tu elección. Haz clic en el card o en Seleccionar paquete para continuar configurándolo.",
    fr: "Parcourez les cartes et sélectionnez l’un des styles disponibles dans le menu déroulant. Les photographies et le prix s’actualisent selon votre choix. Cliquez sur la carte ou sur Sélectionner le forfait pour poursuivre la configuration.",
    pt: "Navegue pelos cards e selecione um dos estilos disponíveis no menu suspenso. As fotografias e o preço são atualizados conforme sua escolha. Clique no card ou em Selecionar pacote para continuar a configuração.",
  },
  proposalIntroStep2Title: {
    en: "Make it personal",
    es: "Personaliza el momento",
    fr: "Personnalisez le moment",
    pt: "Personalize o momento",
  },
  proposalIntroStep2: {
    en: "Review what the package includes and add any available extras. Options and prices depend on the package. Tell us about any special ideas or preferences in your request.",
    es: "Revisa lo que incluye el paquete y añade los extras disponibles. Las opciones y sus precios dependen del paquete elegido. Cuéntanos cualquier idea especial o preferencia en tu solicitud.",
    fr: "Découvrez ce que comprend le forfait et ajoutez les extras disponibles. Les options et leurs prix dépendent du forfait. Faites-nous part de vos idées ou préférences particulières dans votre demande.",
    pt: "Confira o que o pacote inclui e adicione os extras disponíveis. As opções e os preços dependem do pacote. Conte-nos sobre qualquer ideia especial ou preferência na sua solicitação.",
  },
  proposalIntroStep3Title: {
    en: "Review your estimate",
    es: "Revisa tu presupuesto",
    fr: "Vérifiez votre estimation",
    pt: "Revise seu orçamento",
  },
  proposalIntroStep3: {
    en: "The estimated total updates as you change the style or extras. Check the breakdown before continuing. You can switch packages and compare your choices without leaving this page.",
    es: "El total estimado se actualiza al cambiar el estilo o los extras. Revisa el desglose antes de continuar. Puedes cambiar de paquete y comparar tus opciones sin salir de esta página.",
    fr: "Le total estimé s’actualise lorsque vous modifiez le style ou les extras. Vérifiez le détail avant de continuer. Vous pouvez changer de forfait et comparer vos choix sans quitter cette page.",
    pt: "O total estimado é atualizado conforme você muda o estilo ou os extras. Confira o detalhamento antes de continuar. Você pode trocar de pacote e comparar suas opções sem sair desta página.",
  },
  proposalIntroStep4Title: {
    en: "Request availability",
    es: "Consulta disponibilidad",
    fr: "Demandez la disponibilité",
    pt: "Consulte a disponibilidade",
  },
  proposalIntroStep4: {
    en: "Open Check availability, enter your contact details and share your preferred date, hotel and any special requests. Our team will review the chosen configuration and coordinate the details with you.",
    es: "Abre Consultar disponibilidad, completa tus datos de contacto e indica la fecha deseada, tu hotel y cualquier petición especial. Nuestro equipo revisará tu configuración y coordinará contigo los detalles.",
    fr: "Ouvrez Vérifier la disponibilité, saisissez vos coordonnées et indiquez la date souhaitée, votre hôtel et vos demandes particulières. Notre équipe examinera la configuration choisie et organisera les détails avec vous.",
    pt: "Abra Consultar disponibilidade, informe seus dados de contato e indique a data desejada, seu hotel e qualquer pedido especial. Nossa equipe vai analisar a configuração escolhida e combinar os detalhes com você.",
  },
  proposalIntroNote: {
    en: "Submitting a request does not confirm a reservation or take a payment. Availability, the final price and arrangements are confirmed with our team.",
    es: "Enviar una solicitud no confirma una reserva ni realiza un cobro. La disponibilidad, el precio final y los detalles se confirman con nuestro equipo.",
    fr: "L’envoi d’une demande ne confirme pas une réservation et n’entraîne aucun paiement. La disponibilité, le prix final et l’organisation sont confirmés avec notre équipe.",
    pt: "Enviar uma solicitação não confirma uma reserva nem gera cobrança. A disponibilidade, o preço final e os detalhes são confirmados com nossa equipe.",
  },
  dinnerIntroTitle: {
    en: "Candlelit dinners & celebrations in Punta Cana",
    es: "Cenas a la luz de las velas y celebraciones en Punta Cana",
    fr: "Dîners aux chandelles et célébrations à Punta Cana",
    pt: "Jantares à luz de velas e celebrações em Punta Cana",
  },
  dinnerIntroDescription: {
    en: "A table prepared for your special occasion: a birthday, anniversary, marriage proposal, romantic evening or another celebration with the people you love. Personalize the setup, a three-course menu for every guest and the details that make the occasion yours.",
    es: "Una mesa preparada para tu ocasión especial: un cumpleaños, aniversario, propuesta de matrimonio, velada romántica o cualquier otra celebración con las personas que quieres. Personaliza el montaje, un menú de tres tiempos para cada invitado y los detalles que harán tu celebración única.",
    fr: "Une table dressée pour votre occasion spéciale : un anniversaire, un anniversaire de mariage, une demande en mariage, une soirée romantique ou toute autre célébration avec ceux que vous aimez. Personnalisez le décor, un menu en trois plats pour chaque convive et les détails qui feront de cette occasion la vôtre.",
    pt: "Uma mesa preparada para a sua ocasião especial: um aniversário, aniversário de casamento, pedido de casamento, noite romântica ou outra celebração com as pessoas que você ama. Personalize a ambientação, um menu de três tempos para cada convidado e os detalhes que tornam a ocasião única.",
  },
  dinnerIntroStep1Title: {
    en: "Choose the setup and occasion",
    es: "Elige el montaje y la ocasión",
    fr: "Choisissez le décor et l’occasion",
    pt: "Escolha a ambientação e a ocasião",
  },
  dinnerIntroStep1: {
    en: "Explore the three basic setups and their reference photographs. Choose your preferred style, indicate the occasion and indicate the number of guests for our team to review. Use the custom occasion field for a different celebration or a personal message.",
    es: "Explora los tres montajes básicos y sus fotografías de referencia. Elige tu estilo, indica la ocasión y indica el número de invitados para que nuestro equipo lo revise. Usa el campo de ocasión personalizada para otra celebración o un mensaje especial.",
    fr: "Découvrez les trois décors de base et leurs photographies de référence. Choisissez votre style, indiquez l’occasion et le nombre de convives pour que notre équipe les examine. Utilisez le champ d’occasion personnalisée pour une autre célébration ou un message personnel.",
    pt: "Conheça as três ambientações básicas e suas fotografias de referência. Escolha seu estilo preferido, indique a ocasião e o número de convidados para nossa equipe analisar. Use o campo de ocasião personalizada para outra celebração ou uma mensagem pessoal.",
  },
  dinnerIntroStep2Title: {
    en: "Build each guest's menu",
    es: "Prepara el menú de cada persona",
    fr: "Composez le menu de chaque convive",
    pt: "Monte o menu de cada convidado",
  },
  dinnerIntroStep2: {
    en: "Choose a starter, main course and dessert for each guest, plus their welcome cocktail. Vegetarian (V) and vegan (Ve) dishes are marked. Select a red, white or sparkling wine for the experience and tell us about allergies or dietary requirements so we can confirm suitable options.",
    es: "Escoge una entrada, un plato principal y un postre para cada invitado, además de su cóctel de bienvenida. Los platos vegetarianos (V) y veganos (Ve) están identificados. Elige vino tinto, blanco o espumante para la experiencia e informa sobre alergias o necesidades alimentarias para que podamos confirmar opciones adecuadas.",
    fr: "Choisissez une entrée, un plat principal et un dessert pour chaque convive, ainsi que son cocktail de bienvenue. Les plats végétariens (V) et végans (Ve) sont signalés. Sélectionnez un vin rouge, blanc ou effervescent pour l’expérience et indiquez-nous vos allergies ou régimes alimentaires afin que nous puissions confirmer les options adaptées.",
    pt: "Escolha uma entrada, um prato principal e uma sobremesa para cada convidado, além do coquetel de boas-vindas. Os pratos vegetarianos (V) e veganos (Ve) estão identificados. Selecione um vinho tinto, branco ou espumante para a experiência e informe alergias ou restrições alimentares para que possamos confirmar opções adequadas.",
  },
  dinnerIntroStep3Title: {
    en: "Add your finishing touches",
    es: "Añade los detalles especiales",
    fr: "Ajoutez la touche finale",
    pt: "Adicione os toques finais",
  },
  dinnerIntroStep3: {
    en: "Add extras from the available selection. You can also request rose bouquets, premium sparkling wines, chocolates or neon signs such as Happy Anniversary in your message; options not listed require confirmation and a quotation. Transportation from anywhere in Punta Cana is included; share your hotel or pickup location to coordinate it.",
    es: "Añade extras de la selección disponible. También puedes solicitar ramos de rosas, vinos espumantes premium, chocolates o letreros de neón como Happy Anniversary en tu mensaje; las opciones que no aparezcan requieren confirmación y cotización. El transporte desde toda Punta Cana está incluido: indica tu hotel o lugar de recogida para coordinarlo.",
    fr: "Ajoutez des extras parmi la sélection disponible. Vous pouvez aussi demander dans votre message des bouquets de roses, des vins effervescents premium, des chocolats ou des enseignes néon comme Happy Anniversary ; les options non proposées nécessitent une confirmation et un devis. Le transport depuis tout Punta Cana est inclus ; indiquez votre hôtel ou votre lieu de prise en charge pour l’organiser.",
    pt: "Adicione extras da seleção disponível. Você também pode pedir na sua mensagem buquês de rosas, espumantes premium, chocolates ou letreiros neon como Happy Anniversary; opções que não estão na lista exigem confirmação e orçamento. O transporte de qualquer ponto de Punta Cana está incluído; informe seu hotel ou local de embarque para que possamos organizá-lo.",
  },
  dinnerIntroStep4Title: {
    en: "Review and request availability",
    es: "Revisa y consulta disponibilidad",
    fr: "Vérifiez et demandez la disponibilité",
    pt: "Revise e consulte a disponibilidade",
  },
  dinnerIntroStep4: {
    en: "Check the estimated total and its breakdown for guests, menu or drink supplements and selected extras. Complete every guest's menu, then use Request your preferred date to share your contact details, preferred and alternative dates, and celebration requests.",
    es: "Revisa el total estimado y su desglose de invitados, suplementos de comida o bebida y extras seleccionados. Completa el menú de cada persona; después usa Solicita tu fecha preferida para indicar tus datos, la fecha preferida, una alternativa y tus peticiones para la celebración.",
    fr: "Vérifiez le total estimé et son détail : convives, suppléments de menu ou de boissons et extras sélectionnés. Complétez le menu de chaque convive, puis utilisez Demandez votre date préférée pour nous transmettre vos coordonnées, vos dates préférée et alternative, ainsi que vos souhaits pour la célébration.",
    pt: "Confira o total estimado e o detalhamento de convidados, suplementos de menu ou de bebidas e extras selecionados. Complete o menu de cada convidado e, depois, use Solicite sua data preferida para informar seus dados de contato, a data preferida e uma alternativa, além dos seus pedidos para a celebração.",
  },
  dinnerIntroNote: {
    en: "Your request helps us prepare a tailored celebration. It does not confirm a reservation or take a payment: our team will confirm availability, capacity, dietary requirements, transportation and the final price with you.",
    es: "Tu solicitud nos ayuda a preparar una celebración a medida. No confirma una reserva ni realiza un cobro: nuestro equipo confirmará contigo la disponibilidad, la capacidad, las necesidades alimentarias, el transporte y el precio final.",
    fr: "Votre demande nous aide à préparer une célébration sur mesure. Elle ne confirme pas une réservation et n’entraîne aucun paiement : notre équipe confirmera avec vous la disponibilité, la capacité, les régimes alimentaires, le transport et le prix final.",
    pt: "Sua solicitação nos ajuda a preparar uma celebração sob medida. Ela não confirma uma reserva nem gera cobrança: nossa equipe vai confirmar com você a disponibilidade, a capacidade, as restrições alimentares, o transporte e o preço final.",
  },
};
