import type { DefaultText, Locale, Settings } from "./types";
import { introductionLabels } from "./introduction";
import { dinnerPolicyLabels } from "./dinnerPolicy";
export const ui: Record<string, DefaultText> = {
  ...introductionLabels,
  ...dinnerPolicyLabels,
  navHome: { en: "Home", es: "Inicio", fr: "Accueil", pt: "Início" },
  navProposals: {
    en: "Proposal Packages",
    es: "Propuestas",
    fr: "Demandes en mariage",
    pt: "Pedidos de casamento",
  },
  navDinners: {
    en: "Dinners & Celebrations",
    es: "Cenas y celebraciones",
    fr: "Dîners et célébrations",
    pt: "Jantares e celebrações",
  },
  navHow: {
    en: "How It Works",
    es: "Cómo funciona",
    fr: "Comment ça marche",
    pt: "Como funciona",
  },
  navFaq: { en: "FAQ", es: "FAQ", fr: "FAQ", pt: "FAQ" },
  planProposal: {
    en: "Plan your proposal",
    es: "Planea tu propuesta",
    fr: "Préparez votre demande",
    pt: "Planeje seu pedido",
  },
  planCelebration: {
    en: "Plan your celebration",
    es: "Planea tu celebración",
    fr: "Préparez votre célébration",
    pt: "Planeje sua celebração",
  },
  fragranceSensitivity: {
    en: "Fragrance sensitivity — optional",
    es: "Sensibilidad a fragancias — opcional",
    fr: "Sensibilité aux parfums — facultatif",
    pt: "Sensibilidade a fragrâncias — opcional",
  },
  occasionGuests: {
    en: "Occasion & guests",
    es: "Ocasión e invitados",
    fr: "Occasion et convives",
    pt: "Ocasião e convidados",
  },
  foodMenu: {
    en: "Food menu",
    es: "Menú de comida",
    fr: "Menu",
    pt: "Cardápio",
  },
  drinksWine: {
    en: "Drinks & wine",
    es: "Bebidas y vinos",
    fr: "Boissons et vins",
    pt: "Bebidas e vinhos",
  },
  welcomeCocktail: {
    en: "Welcome cocktail",
    es: "Cóctel de bienvenida",
    fr: "Cocktail de bienvenue",
    pt: "Coquetel de boas-vindas",
  },
  wineSelection: {
    en: "Wine selection · per experience",
    es: "Selección de vino · por experiencia",
    fr: "Sélection de vin · par expérience",
    pt: "Seleção de vinho · por experiência",
  },
  menusCompleted: {
    en: "menus completed",
    es: "menús completos",
    fr: "menus complétés",
    pt: "menus concluídos",
  },
  chooseMenu: {
    en: "Choose menu",
    es: "Elige el menú",
    fr: "Choisir le menu",
    pt: "Escolher o menu",
  },
  menuSelected: {
    en: "Menu selected ✓",
    es: "Menú seleccionado ✓",
    fr: "Menu sélectionné ✓",
    pt: "Menu selecionado ✓",
  },
  priceDetails: {
    en: "Price details",
    es: "Desglose del precio",
    fr: "Détail du prix",
    pt: "Detalhamento do preço",
  },
  baseExperience: {
    en: "Base experience",
    es: "Experiencia base",
    fr: "Expérience de base",
    pt: "Experiência base",
  },
  additionalGuests: {
    en: "Additional guests",
    es: "Invitados adicionales",
    fr: "Convives supplémentaires",
    pt: "Convidados adicionais",
  },
  menuSupplements: {
    en: "Menu supplements",
    es: "Suplementos del menú",
    fr: "Suppléments menu",
    pt: "Suplementos do menu",
  },
  drinkSupplements: {
    en: "Drink supplements",
    es: "Suplementos de bebidas",
    fr: "Suppléments boissons",
    pt: "Suplementos de bebidas",
  },
  extras: { en: "Extras", es: "Extras", fr: "Extras", pt: "Extras" },
  addGuest: {
    en: "Add guest",
    es: "Añadir invitado",
    fr: "Ajouter un convive",
    pt: "Adicionar convidado",
  },
  removeGuest: {
    en: "Remove guest",
    es: "Quitar invitado",
    fr: "Retirer un convive",
    pt: "Remover convidado",
  },
  noExtras: {
    en: "No extras selected",
    es: "Sin extras seleccionados",
    fr: "Aucun extra sélectionné",
    pt: "Nenhum extra selecionado",
  },
  cocktails: {
    en: "cocktails",
    es: "cócteles",
    fr: "cocktails",
    pt: "coquetéis",
  },
  cocktailHint: {
    en: "Choose each welcome cocktail in the guest menu.",
    es: "Elige cada cóctel de bienvenida en el menú del invitado.",
    fr: "Choisissez chaque cocktail de bienvenue dans le menu du convive.",
    pt: "Escolha cada coquetel de boas-vindas no menu do convidado.",
  },
  completeHint: {
    en: "Complete each guest menu to check availability.",
    es: "Completa el menú de cada invitado para consultar disponibilidad.",
    fr: "Complétez le menu de chaque convive pour vérifier la disponibilité.",
    pt: "Complete o menu de cada convidado para consultar a disponibilidade.",
  },
  capacityPending: {
    en: "Additional capacity awaiting confirmation.",
    es: "Capacidad adicional pendiente de confirmar.",
    fr: "Capacité supplémentaire en attente de confirmation.",
    pt: "Capacidade adicional aguardando confirmação.",
  },
  vegan: { en: "Vegan", es: "Vegano", fr: "Végan", pt: "Vegano" },
  vegetarian: {
    en: "Vegetarian",
    es: "Vegetariano",
    fr: "Végétarien",
    pt: "Vegetariano",
  },
  proposalSectionTitle: {
    en: "Proposals",
    es: "Propuestas",
    fr: "Demandes en mariage",
    pt: "Pedidos de casamento",
  },
  dinnerSectionTitle: {
    en: "Punta Cana Romantic Dinners",
    es: "Cenas románticas en Punta Cana",
    fr: "Dîners romantiques à Punta Cana",
    pt: "Jantares românticos em Punta Cana",
  },
  estimatedTotalLabel: {
    en: "Estimated total",
    es: "Total estimado",
    fr: "Total estimé",
    pt: "Total estimado",
  },
  availabilityButtonLabel: {
    en: "Check availability",
    es: "Consultar disponibilidad",
    fr: "Vérifier la disponibilité",
    pt: "Consultar disponibilidade",
  },
  includedLabel: {
    en: "Included",
    es: "Incluido",
    fr: "Inclus",
    pt: "Incluído",
  },
  startingAtLabel: {
    en: "Starting at",
    es: "Desde",
    fr: "À partir de",
    pt: "A partir de",
  },
  selectStyleLabel: {
    en: "Choose your style",
    es: "Elige tu estilo",
    fr: "Choisissez votre style",
    pt: "Escolha seu estilo",
  },
  contactUsLabel: {
    en: "Contact us",
    es: "Contáctanos",
    fr: "Contactez-nous",
    pt: "Fale conosco",
  },
  emptyProposals: {
    en: "No proposals available.",
    es: "No hay propuestas disponibles.",
    fr: "Aucune demande en mariage disponible.",
    pt: "Nenhum pedido de casamento disponível.",
  },
  emptyDinners: {
    en: "No romantic dinners available.",
    es: "No hay cenas románticas disponibles.",
    fr: "Aucun dîner romantique disponible.",
    pt: "Nenhum jantar romântico disponível.",
  },
  fullName: {
    en: "Full name",
    es: "Nombre completo",
    fr: "Nom complet",
    pt: "Nome completo",
  },
  email: { en: "Email", es: "Correo electrónico", fr: "E-mail", pt: "E-mail" },
  phone: {
    en: "Phone / WhatsApp",
    es: "Teléfono / WhatsApp",
    fr: "Téléphone / WhatsApp",
    pt: "Telefone / WhatsApp",
  },
  send: {
    en: "Send request",
    es: "Enviar solicitud",
    fr: "Envoyer la demande",
    pt: "Enviar solicitação",
  },
  success: {
    en: "Request received.",
    es: "Solicitud recibida.",
    fr: "Demande reçue.",
    pt: "Solicitação recebida.",
  },
  error: {
    en: "Unable to send. Please try again or contact us directly.",
    es: "No se pudo enviar. Inténtalo de nuevo o contáctanos directamente.",
    fr: "Envoi impossible. Veuillez réessayer ou nous contacter directement.",
    pt: "Não foi possível enviar. Tente novamente ou fale conosco diretamente.",
  },
  guests: { en: "Guests", es: "Invitados", fr: "Convives", pt: "Convidados" },
  guest: { en: "Guest", es: "Invitado", fr: "Convive", pt: "Convidado" },
  occasion: { en: "Occasion", es: "Ocasión", fr: "Occasion", pt: "Ocasião" },
  customOccasion: {
    en: "Custom occasion / message",
    es: "Ocasión personalizada / mensaje",
    fr: "Occasion personnalisée / message",
    pt: "Ocasião personalizada / mensagem",
  },
  starter: { en: "Starter", es: "Entrada", fr: "Entrée", pt: "Entrada" },
  main: {
    en: "Main",
    es: "Plato principal",
    fr: "Plat principal",
    pt: "Prato principal",
  },
  dessert: { en: "Dessert", es: "Postre", fr: "Dessert", pt: "Sobremesa" },
  duration: { en: "Duration", es: "Duración", fr: "Durée", pt: "Duração" },
  minutes: { en: "minutes", es: "minutos", fr: "minutes", pt: "minutos" },
  quantity: {
    en: "Quantity",
    es: "Cantidad",
    fr: "Quantité",
    pt: "Quantidade",
  },
  quotePending: {
    en: "Additional services pending quotation",
    es: "Servicios adicionales pendientes de cotización",
    fr: "Services supplémentaires en attente de devis",
    pt: "Serviços adicionais aguardando orçamento",
  },
  select: {
    en: "Select",
    es: "Selecciona",
    fr: "Sélectionner",
    pt: "Selecionar",
  },
  menu: { en: "Menu", es: "Menú", fr: "Menu", pt: "Menu" },
  previous: {
    en: "Previous photo",
    es: "Foto anterior",
    fr: "Photo précédente",
    pt: "Foto anterior",
  },
  next: {
    en: "Next photo",
    es: "Foto siguiente",
    fr: "Photo suivante",
    pt: "Próxima foto",
  },
  photo: { en: "Photo", es: "Foto", fr: "Photo", pt: "Foto" },
  selectPackage: {
    en: "Select package",
    es: "Seleccionar paquete",
    fr: "Sélectionner le forfait",
    pt: "Selecionar pacote",
  },
  selectedPackage: {
    en: "Package selected",
    es: "Paquete seleccionado",
    fr: "Forfait sélectionné",
    pt: "Pacote selecionado",
  },
  blog: { en: "Blog", es: "Blog", fr: "Blog", pt: "Blog" },
  faq: {
    en: "Frequently asked questions",
    es: "Preguntas frecuentes",
    fr: "Questions fréquentes",
    pt: "Perguntas frequentes",
  },
  previewOnly: {
    en: "Preview only · no request will be sent",
    es: "Solo vista previa · no se enviará ninguna solicitud",
    fr: "Aperçu uniquement · aucune demande ne sera envoyée",
    pt: "Apenas pré-visualização · nenhuma solicitação será enviada",
  },
  privacy: {
    en: "Privacy policy",
    es: "Política de privacidad",
    fr: "Politique de confidentialité",
    pt: "Política de privacidade",
  },
  terms: {
    en: "Terms of service",
    es: "Términos de servicio",
    fr: "Conditions d’utilisation",
    pt: "Termos de serviço",
  },
  footerExplore: {
    en: "Explore",
    es: "Descubre",
    fr: "Découvrir",
    pt: "Explorar",
  },
  footerContact: {
    en: "Contact",
    es: "Contacto",
    fr: "Contact",
    pt: "Contato",
  },
  rightsReserved: {
    en: "All rights reserved.",
    es: "Todos los derechos reservados.",
    fr: "Tous droits réservés.",
    pt: "Todos os direitos reservados.",
  },
  siteLinks: {
    en: "Site links",
    es: "Enlaces del sitio",
    fr: "Liens du site",
    pt: "Links do site",
  },
  close: { en: "Close", es: "Cerrar", fr: "Fermer", pt: "Fechar" },
  introStepsHeading: {
    en: "Your experience, step by step",
    es: "Tu experiencia, paso a paso",
    fr: "Votre expérience, étape par étape",
    pt: "Sua experiência, passo a passo",
  },
  priceToBeDefined: {
    en: "Price to be defined",
    es: "Precio por definir",
    fr: "Prix à définir",
    pt: "Preço a definir",
  },
  setupTemplate: {
    en: "Setup template",
    es: "Plantilla de montaje",
    fr: "Modèle de décor",
    pt: "Modelo de ambientação",
  },
  photoPending: {
    en: "Real photograph to be added in Sanity",
    es: "Fotografía real pendiente de cargar en Sanity",
    fr: "Photographie réelle à ajouter dans Sanity",
    pt: "Fotografia real a ser adicionada no Sanity",
  },
  dinnerTemplatePreviewNote: {
    en: "Editable example · Three setups with reference images from Sanity. Menu and prices configured; final capacity awaiting confirmation.",
    es: "Ejemplo editable · Tres montajes con imágenes de referencia de Sanity. Menú y tarifas configurados; capacidad final pendiente de confirmar.",
    fr: "Exemple modifiable · Trois décors avec des images de référence issues de Sanity. Menu et prix configurés ; capacité finale en attente de confirmation.",
    pt: "Exemplo editável · Três ambientações com imagens de referência do Sanity. Menu e preços configurados; capacidade final aguardando confirmação.",
  },
  dinnerInquiryNote: {
    en: "Personalize your dinner and send us your preferred date. Our team will personally confirm capacity and availability for your celebration.",
    es: "Personaliza tu cena y envíanos tu fecha preferida. Nuestro equipo confirmará personalmente la capacidad y disponibilidad de tu celebración.",
    fr: "Personnalisez votre dîner et envoyez-nous votre date préférée. Notre équipe confirmera personnellement la capacité et la disponibilité pour votre célébration.",
    pt: "Personalize seu jantar e envie sua data preferida. Nossa equipe confirmará pessoalmente a capacidade e a disponibilidade para a sua celebração.",
  },
  heroEyebrow: {
    en: "Extraordinary moments",
    es: "Momentos extraordinarios",
    fr: "Moments d’exception",
    pt: "Momentos extraordinários",
  },
  dinnerHeroText: {
    en: "By candlelight, beside the sea. A table to celebrate your way.",
    es: "A la luz de las velas, frente al mar. Una mesa para celebrar a tu manera.",
    fr: "Aux chandelles, face à la mer. Une table pour célébrer à votre façon.",
    pt: "À luz de velas, de frente para o mar. Uma mesa para celebrar do seu jeito.",
  },
  proposalHeroText: {
    en: "An unforgettable setting for the beginning of your story. Every detail, chosen by you.",
    es: "Un escenario inolvidable para el comienzo de su historia. Cada detalle, elegido por ti.",
    fr: "Un cadre inoubliable pour le début de votre histoire. Chaque détail, choisi par vous.",
    pt: "Um cenário inesquecível para o começo da história de vocês. Cada detalhe, escolhido por você.",
  },
  dinnerHeroCta: {
    en: "Choose your setting",
    es: "Elige tu montaje",
    fr: "Choisissez votre décor",
    pt: "Escolha sua ambientação",
  },
  proposalHeroCta: {
    en: "Explore the packages",
    es: "Descubre los paquetes",
    fr: "Découvrir les forfaits",
    pt: "Conheça os pacotes",
  },
  heroHowItWorks: {
    en: "How it works",
    es: "Cómo funciona",
    fr: "Comment ça marche",
    pt: "Como funciona",
  },
  proposalDinnerEyebrow: {
    en: "A table for two · Three courses",
    es: "Una mesa para dos · Tres tiempos",
    fr: "Une table pour deux · Trois plats",
    pt: "Uma mesa para dois · Três tempos",
  },
  proposalDinnerTitle: {
    en: "The perfect ending to your proposal",
    es: "El final perfecto para tu propuesta",
    fr: "La conclusion parfaite de votre demande",
    pt: "O final perfeito para o seu pedido",
  },
  proposalDinnerIntro: {
    en: "Choose a starter, main course and dessert for each guest.",
    es: "Elige una entrada, un plato principal y un postre para cada invitado.",
    fr: "Choisissez une entrée, un plat principal et un dessert pour chaque convive.",
    pt: "Escolha uma entrada, um prato principal e uma sobremesa para cada convidado.",
  },
  dietaryLegend: {
    en: "V: vegetarian · Ve: vegan",
    es: "V: vegetariano · Ve: vegano",
    fr: "V : végétarien · Ve : végan",
    pt: "V: vegetariano · Ve: vegano",
  },
};
export function label(
  settings: Settings | null | undefined,
  locale: Locale,
  key: string,
) {
  const edited = settings?.[key];
  // The editor's text (settings are one document per language), then the
  // built-in text in `locale`, then in English.
  return (
    (typeof edited === "string" && edited) ||
    ui[key]?.[locale] ||
    ui[key]?.en ||
    ""
  );
}
