import type { Locale, Settings } from "./types";
export const ui: Record<string, [string, string]> = {
  occasionGuests: ["Occasion & guests", "Ocasión e invitados"],
  foodMenu: ["Food menu", "Menú de comida"],
  drinksWine: ["Drinks & wine", "Bebidas y vinos"],
  welcomeCocktail: ["Welcome cocktail", "Cóctel de bienvenida"],
  wineSelection: [
    "Wine selection · per experience",
    "Selección de vino · por experiencia",
  ],
  menusCompleted: ["menus completed", "menús completos"],
  chooseMenu: ["Choose menu", "Elige el menú"],
  menuSelected: ["Menu selected ✓", "Menú seleccionado ✓"],
  priceDetails: ["Price details", "Desglose del precio"],
  baseExperience: ["Base experience", "Experiencia base"],
  additionalGuests: ["Additional guests", "Invitados adicionales"],
  menuSupplements: ["Menu supplements", "Suplementos del menú"],
  drinkSupplements: ["Drink supplements", "Suplementos de bebidas"],
  extras: ["Extras", "Extras"],
  addGuest: ["Add guest", "Añadir invitado"],
  removeGuest: ["Remove guest", "Quitar invitado"],
  noExtras: ["No extras selected", "Sin extras seleccionados"],
  cocktails: ["cocktails", "cócteles"],
  cocktailHint: [
    "Choose each welcome cocktail in the guest menu.",
    "Elige cada cóctel de bienvenida en el menú del invitado.",
  ],
  completeHint: [
    "Complete each guest menu to check availability.",
    "Completa el menú de cada invitado para consultar disponibilidad.",
  ],
  capacityPending: [
    "Additional capacity awaiting confirmation.",
    "Capacidad adicional pendiente de confirmar.",
  ],
  vegan: ["Vegan", "Vegano"],
  vegetarian: ["Vegetarian", "Vegetariano"],
  proposalSectionTitle: ["Proposals", "Propuestas"],
  dinnerSectionTitle: [
    "Punta Cana Romantic Dinners",
    "Cenas románticas en Punta Cana",
  ],
  estimatedTotalLabel: ["Estimated total", "Total estimado"],
  availabilityButtonLabel: ["Check availability", "Consultar disponibilidad"],
  includedLabel: ["Included", "Incluido"],
  startingAtLabel: ["Starting at", "Desde"],
  selectStyleLabel: ["Choose your style", "Elige tu estilo"],
  addonsLabel: ["Add extras", "Añadir extras"],
  contactUsLabel: ["Contact us", "Contáctanos"],
  emptyProposals: ["No proposals available.", "No hay propuestas disponibles."],
  emptyDinners: [
    "No romantic dinners available.",
    "No hay cenas románticas disponibles.",
  ],
  fullName: ["Full name", "Nombre completo"],
  email: ["Email", "Correo electrónico"],
  phone: ["Phone / WhatsApp", "Teléfono / WhatsApp"],
  hotel: ["Hotel (optional)", "Hotel (opcional)"],
  desiredDate: ["Date (optional)", "Fecha (opcional)"],
  notes: ["Message", "Mensaje"],
  send: ["Send request", "Enviar solicitud"],
  success: ["Request received.", "Solicitud recibida."],
  error: [
    "Unable to send. Please try again or contact us directly.",
    "No se pudo enviar. Inténtalo de nuevo o contáctanos directamente.",
  ],
  guests: ["Guests", "Invitados"],
  guest: ["Guest", "Invitado"],
  occasion: ["Occasion", "Ocasión"],
  customOccasion: [
    "Custom occasion / message",
    "Ocasión personalizada / mensaje",
  ],
  starter: ["Starter", "Entrada"],
  main: ["Main", "Plato principal"],
  dessert: ["Dessert", "Postre"],
  beverages: ["Beverages", "Bebidas"],
  duration: ["Duration", "Duración"],
  minutes: ["minutes", "minutos"],
  quantity: ["Quantity", "Cantidad"],
  quotePending: [
    "Additional services pending quotation",
    "Servicios adicionales pendientes de cotización",
  ],
  select: ["Select", "Selecciona"],
  menu: ["Menu", "Menú"],
  previous: ["Previous photo", "Foto anterior"],
  next: ["Next photo", "Foto siguiente"],
  photo: ["Photo", "Foto"],
  blog: ["Blog", "Blog"],
  faq: ["Frequently asked questions", "Preguntas frecuentes"],
  previewOnly: [
    "Preview only · no request will be sent",
    "Solo vista previa · no se enviará ninguna solicitud",
  ],
  privacy: ["Privacy policy", "Política de privacidad"],
  terms: ["Terms of service", "Términos de servicio"],
};
export function label(
  settings: Settings | null | undefined,
  locale: Locale,
  key: string,
) {
  return settings?.[key]?.[locale] || ui[key]?.[locale === "es" ? 1 : 0] || "";
}
